# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

admm <- function(x, y, lambda, max_passes, opt) {
    .Call(`_slopesolvers_admm`, x, y, lambda, max_passes, opt)
}

#' Logistic regression with ADMM
#'
#' @param x predictors
#' @param y response in {-1, 1}
#' @param lambda regularization sequence
#' @param max_passes maximum number of passes
#' @param opt optimal value
#' @param opt_tol relative suboptimality tolerance
#' @export
admm_binom <- function(x, y, lambda, max_passes, opt, opt_tol = 1e-4) {
    .Call(`_slopesolvers_admm_binom`, x, y, lambda, max_passes, opt, opt_tol)
}

admmEigen <- function(x, y, lambda, max_passes, opt) {
    .Call(`_slopesolvers_admmEigen`, x, y, lambda, max_passes, opt)
}

amp <- function(x, y, lambda, max_passes, opt) {
    .Call(`_slopesolvers_amp`, x, y, lambda, max_passes, opt)
}

cd <- function(x, y, lambda, max_passes) {
    .Call(`_slopesolvers_cd`, x, y, lambda, max_passes)
}

drs <- function(x, y, lambda, max_passes, epsilon, opt) {
    .Call(`_slopesolvers_drs`, x, y, lambda, max_passes, epsilon, opt)
}

fista_backtracking <- function(x, y, lambda, max_passes, epsilon, type, opt) {
    .Call(`_slopesolvers_fista_backtracking`, x, y, lambda, max_passes, epsilon, type, opt)
}

fista_binom <- function(x, y, lambda, max_passes, opt) {
    .Call(`_slopesolvers_fista_binom`, x, y, lambda, max_passes, opt)
}

pn_binom <- function(A, b, lambda, max_passes, opt) {
    .Call(`_slopesolvers_pn_binom`, A, b, lambda, max_passes, opt)
}

sparsa <- function(x, y, lambda, max_passes, epsilon, opt) {
    .Call(`_slopesolvers_sparsa`, x, y, lambda, max_passes, epsilon, opt)
}

